#!/bin/sh

set -e

DIR=$(pwd)
UNIT_LOG_FILE='/var/log/unit.log'
UNIT_ACCESS_LOG_FILE='/var/log/access.log'
UNIT_PID_FILE='/run/unit.pid'
UNIT_SOCKET_FILE='/run/control.unit.sock'

# Clear/warm-up Symfony cache
if [ "$CACHE_CLEAR_BEFORE_START" = true ]; then
  "${DIR}bin/console" cache:clear --no-interaction # Todo: Configure alternative for Nette
fi

# Forward Unit log to stdout
touch "$UNIT_LOG_FILE"
touch "$UNIT_ACCESS_LOG_FILE"
ln -sf /proc/1/fd/1 "$UNIT_LOG_FILE"
ln -sf /proc/1/fd/1 "$UNIT_ACCESS_LOG_FILE"

# Start Unit web application server
unitd --control "unix:${UNIT_SOCKET_FILE}" \
  --log "$UNIT_LOG_FILE" \
  --pid "$UNIT_PID_FILE"

# Wait until Unit daemon is ready
while [ ! -S "$UNIT_SOCKET_FILE" ]; do /bin/sleep 0.5; done

# Apply Unit server configuration
curl -X PUT \
  --data-binary @/docker-entrypoint.d/settings.json \
  --unix-socket "$UNIT_SOCKET_FILE" \
  --output /dev/null \
  --silent \
  http://localhost/config

# Keep container running until Unit process finish
while true; do /bin/sleep 1000; done
